# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-27 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', models.TextField(blank=True, verbose_name='文章内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '博客文章表',
                'ordering': ['create_time'],
                'verbose_name_plural': '博客文章表',
                'db_table': 'bl_blog_content',
            },
        ),
        migrations.CreateModel(
            name='BlogSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '博客分类表',
                'ordering': ['create_time'],
                'verbose_name_plural': '博客分类表',
                'db_table': 'bl_blog_sort',
            },
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='sort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BlogSort', to='myblog.BlogSort'),
        ),
    ]
