# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-27 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe6\xa0\x87\xe9\xa2\x98')),
                ('content', models.TextField(blank=True, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe5\x86\x85\xe5\xae\xb9')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'bl_blog_content',
                'verbose_name': '\u535a\u5ba2\u6587\u7ae0\u8868',
                'verbose_name_plural': '\u535a\u5ba2\u6587\u7ae0\u8868',
            },
        ),
        migrations.CreateModel(
            name='BlogSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe5\x90\x8d\xe7\xa7\xb0')),
                ('description', models.TextField(blank=True, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('blog_type', models.CharField(default=0, max_length=2, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'bl_blog_sort',
                'verbose_name': '\u535a\u5ba2\u5206\u7c7b\u8868',
                'verbose_name_plural': '\u535a\u5ba2\u5206\u7c7b\u8868',
            },
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='sort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BlogSort', to='myblog.BlogSort'),
        ),
    ]
