# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-30 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20180727_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcontent',
            options={'ordering': ['-create_time'], 'verbose_name': '博客文章表', 'verbose_name_plural': '博客文章表'},
        ),
        migrations.AlterModelOptions(
            name='blogsort',
            options={'ordering': ['-create_time'], 'verbose_name': '博客分类表', 'verbose_name_plural': '博客分类表'},
        ),
        migrations.AddField(
            model_name='blogsort',
            name='blog_type',
            field=models.CharField(default=0, max_length=2, verbose_name='类型'),
        ),
    ]
