# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-03 02:09
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20180830_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='文章内容'),
        ),
    ]
