# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-05 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20180903_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='content',
            field=models.TextField(blank=True, verbose_name='文章内容'),
        ),
    ]
